##########
## FAIL ##
##########
- conditions:
    success: false
  actions:
    rename: "!Failed"


##############
## LEGACIES ##
##############
- conditions:
    legacy: true
    appraised: false
    iv:
  actions:
    appraise:
- conditions:
    legacy: true
    name__in: !include ../pokemons/legendaries.yaml
    iv_max__gt: 90
  actions:
    favorite:
    rename: "·{calcy}"
- conditions:
    legacy: true
  actions:
    favorite:
    rename: '•{calcy}'


##############
## SPECIFIC ##
##############
## Renames unowns to be renamed afterwards with emi_unowns.yaml
- conditions:
    name__in:
      - Unown
  actions:
    rename: "* The {iv_avg}"


## Appraises luckies
- conditions:
    lucky: true
    iv:
    appraised: false
  actions:
    appraise:


## Renames babies to be renamed afterwards with emi_prettify.yaml
## only if IV is greater than 90
- conditions:
    name__in: !include ../pokemons/babies.yaml
    iv_max__ge: 93
  actions:
    rename: "*{name}{iv_avg}"

## Renames random rare & bizarre stuff and those "one-time only"
## pokémons to be renamed afterwards with emi_prettify.yaml
- conditions:
    name__in: !include ../pokemons/rares.yaml
  actions:
    rename: "*{name}{iv_avg}"


## Legendaries and stuff
- conditions:
    iv:
    iv_max__gt: 90
    name__in: !include ../pokemons/legendaries.yaml
    appraised: false
  actions:
    appraise:
- conditions:
    name__in: !include ../pokemons/legendaries.yaml
    iv_max__gt: 90
  actions:
    rename: "·{calcy}" # Good ones get custom prefix
- conditions:
    name__in: !include ../pokemons/legendaries.yaml
  actions:
    rename: "•{calcy}"  # The rest of them (IV <90), gets renamed without prefix


##############
### HUNDOS ###
##############
# Check possible IV100
- conditions:
    iv:
    iv_max__ge: 100
    appraised: false
  actions:
    appraise:
# If even after appraisal is not clear, rename for manual check:
- conditions:
    iv_min__lt: 100
    iv_max__eq: 100
    appraised: true
  actions:
    rename: "%{calcy}"
# Guaranteed hundos get renamed normally
- conditions:
    iv__eq: 100
  actions:
    rename: "•{calcy}"


#####################
### META RELEVANT ###
#####################
# Meta-relevant high LVL AND highish IV get renamed normally
# Every other meta-relevant combination (low LVL OR low IV),
# we'll trade it on the block TRADES below
- conditions:
    iv_max__ge: 90
    level__ge: 30
    name__in: !include ../pokemons/metarelevant.yaml
  actions:
    rename: "•{calcy}"

###########
### PVP ###
###########
# This is an experiment
- conditions:
    name__in: !include ../pokemons/pvp.yaml
    attack_iv__le: 1
    defense_iv__ge: 8
    hp_iv__ge: 8
  actions:
    rename: "$PVP{attack_iv}-{defense_iv}-{hp_iv}"


##############
### TRADES ###
##############
# Renames pokemons to trade for candies
- conditions:
    name__in: !include ../pokemons/trade_candy.yaml
    lucky: false
  actions:
    rename: "π{level} TRADE"

# This one is for trading metarelevants with low level and IVs lower than 90
- conditions:
    level__lt: 30
    iv_max__lt: 90
    name__in: !include ../pokemons/metarelevant.yaml
    lucky: false
  actions:
    rename: "μ{level} TRAD {iv_max}"

# This one is for trading metarelevants with low IV and any LVL whatsoever
- conditions:
    iv_max__lt: 90
    name__in: !include ../pokemons/metarelevant.yaml
    lucky: false
  actions:
    rename: "μ{level} TRAD {iv_max}"

####################
### EVOLVE POKES ###
####################
# These are pokemons for mass evolving (12 candy per pokémon), which you
# should rather trade before mass evolving so you get even more candies! :D
# - conditions:
#     name__in: !include ../pokemons/evolve.yaml
#   actions:
#     rename: "Ω TRADEVO"


#######################
### SKIPS AND TRASH ###
#######################
# Any left lucky gets manually verified
- conditions:
    lucky: true
  actions:
    rename: "! {calcy}"

# Any left higher than 95 iv gets checked and if
# truly iv > 95 gets renamed for manual check
- conditions:
    iv_max__ge: 95
  actions:
    appraise:
    rename: "! {calcy}"

# Any left less than 95 iv gets skipped
- conditions:
    iv_max__lt: 95
# In particular cases (like when one of the accounts does not have too many pokémons
# to trade), you might want to rename anything left for trading, instead of skipping.
# To do it so, uncomment both line below
  # actions:
    # rename: "⇆ {level} TRADE"


# This renames anything else that doesn't match any rule above
# which, in theory, shouldn't happen. So if you see a pokemon with
# this character you know you have a mistake on this file and most
# likely missed something.
- actions:
    rename: "¿ {calcy}"
