## This renames what I consider "special" pokémon, like babies,
## random, rare, and one-time only pokémons. The full lists would be
## the ones in lists babies.yaml and rares.yaml + eggsonly + mythical.

## How to use:
# 1. Set calcy as:
# - No Moves:
#    "$Name$$Form$$Legacy$$IV%Avg$            $CatchDate$|$Lucky$|$ATT$|$DEF$|$HP$|$Gender$|$Trade$|$IV%Min$|$IV%Max$|$AttIV$|$DefIV$|$HpIV$|$FaMove$|$SpMove$|$Appraised$|$Legacy$"
# - Moves:
#    "$Name$$Form$$Legacy$$IV%Avg$            $CatchDate$|$Lucky$|$ATT$|$DEF$|$HP$|$Gender$|$Trade$|$IV%Min$|$IV%Max$|$AttIV$|$DefIV$|$HpIV$|$FaMove$|$SpMove$|$Appraised$|$Legacy$"
# 2. Search for:
#    "eggsonly,mythical,shinx,spinda,spiritomb,shedinja&!deoxys&!shiny&!costume"
# 3. Run the renamer with this config
#
# TIP: You can also restore calcy's export: shiny.properties instead of copying and pasting the strings above.
#      Be aware it's going to replace your symbols as well.



# Nobrainer:
- conditions:
    success: false
  actions:
    rename: "! Verify"

# Appraise everyhing that's not appraised yet
- conditions:
    appraised: false
  actions:
    appraise:

## Renames babies with hearts ...
##    .... because babies.
- conditions:
    name__in: !include ../pokemons/babies.yaml
  actions:
    rename: "♥{calcy}"

## Renames random rare & bizarre stuff and
## those "one-time only" pokémons
- conditions:
    name__in: !include ../pokemons/rares.yaml
  actions:
    rename: "♣{calcy}"

## Everything else is neither baby nor rare, so..?
- actions:
    rename: "♠{calcy}"
