## Locations for Redmi Note 5 with density override 408

rename: [540, 920]
next: [1000, 600]
rename_ok: [550, 1170]
close_calcy_dialog: [1010, 1505]   # watch out, this can't be on top of power up or bad things will happen
favorite_button: [970, 190]
favorite_button_box: [955, 175, 995, 200]
pokemon_menu_button: [930, 2020]
appraise_button: [940, 1620]
continue_appraisal: [550, 1415]
calcy_appraisal_save_button: [870, 870]
dismiss_calcy: [540, 1230]
appraisal_box: [70, 1920, 1020, 2090]
scroll_to_moves: [50, 2010, 50, 1200]
scroll_to_top: [50, 1100, 50, 2010]