locations:
  !include config/locations/redmi.yaml

waits:
  !include config/waits/redmi.yaml

blacklist:
  -
  #disabled because of https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/issues/47
  #!include config/blacklist.yaml


## Select below which action file you'd like to use:
#  default:   For main account
#  alt:       For alt account
#  prettify:  For main after renaming with default:
#               1. Filter by '*,shiny,list-of-babies,list-of-rares' (get it on prettify.yaml)
#               2. Run this
#  traded:    For main and alt *after* trading lots of pokes:
#               1. Filter by 'trade'
#               2. Run this
#  unown:     For main account:
#               1. Filter by 'unown'
#               2. Set calcy as: 'The $IV_AVG$'
#               3. Run this
## *Take a look at those yamls yourself, so you understand better how this works*
actions:
  !include config/actions/default.yaml


## How trading symbols (should, threoretically) work:
# π is for safe trading (automated, shouldn't trade anything special)
# Ω is for evo pokes (for using lucky egg). You can trade them for candy,
#   alongside π, and then evolve the already traded ones! :D
# μ are not-that-safe pokemons for auto-trading. I'd advise trading π for π only, so it's fair.
