## This is the most recent list of baby pokemon
# Last update: 2019-08-30
# Taken from https://pokemongo.fandom.com/wiki/Pok%C3%A9mon#Baby_Pok.C3.A9mon
- Pichu
- Cleffa
- Igglybuff
- Togepi
- Tyrogue
- Smoochum
- Elekid
- Magby
- Azurill
- Wynaut
- Budew
- Chingling
- Bonsly
- Mime Jr.
- Happiny
- Munchlax
- Riolu
- Mantyke
- Shinx