- Tyranitar
- Dragonite
- Blissey
- Salamence
- Metagross
- Machamp
- Slaking
- Snorlax
- Gengar
- Gallade
- Hariyama
- Gardevoir
- Venusaur
- Rampardos
- Garchomp
- Mamoswine
- Chansey
- Milotic
- Rhyperior
- Roserade
- Magmortar
- Blaziken