- Eevee
- Umbreon

- Slakoth
- Vigoroth

- Bronzor
- Bronzong

- Lugia

- Togepi
- Togetic

- Shieldon
- Bastiodon

- Skarmory

- Bayleef # iv 100 - great
- Meganium # iv 100 - ultra

- Marill
- Azumarill

- Lapras

- Munchlax
- Tropius
- Dragonair

- Chinchou
- Lanturn

- Poliwag
- Poliwhirl
- Politoed

- Hoothoot
- Noctowl

- Tyrogue
- Hitmontop

- Sableye # IV 100, LVL40
- Medicham # Evo: Medicham, IV100, LVL40
