# Random, rare, mythical, one-time-only and so-on.
# Usually you want them regardless of IVs.
- Spiritomb
- Spinda
- Shedinja
- Celebi
- Mew
- Meltan
- Melmetal
- Chimecho
- Carnivine
- Delibird
- Ditto
- Pachirisu