- Larvitar
- Pupitar

- Dratini
- Dragonair

- Chansey

- Bagon
- Shelgon

- Beldum
- Metang

- Ralts
- Kirlia

- Slakoth
- Vigoroth

- Marowak Alolan
- Raichu Alolan
- Mawile
- Absol
- Porygon
- Lickitung
- Pineco
- Trapinch

## Bad babies but good for candy:
- Riolu
- Happiny
- Shinx
- Togepi
- Munchlax
- Chingling

- Cherrim Overcast
- Cherrim Sunshine
- Gible
- Gabite
- Cherubi
- Shellos
- Hippopotas
- Burmy

## You can delete pokemons above, but I guess most people would
## would agree that those are tradeable for extra candies.

## Add your own below:
- Cranidos
- Shieldon
- Torchic
- Gastly
- Aerodactyl
- Ralts
- Kirlia