## These are pokés that you want to trade
## **from ALT to MAIN**
## The only benefit is that the alt will get candies (big deal),
## *and* that you *could* get lucky and get a lucky trade.

- Meowth Alolan
- Vulpix Alolan
- Grimer Alolan
- Sandshrew Alolan
- Marowak Alolan
- Raichu Alolan
- Mawile
- Absol
- Smeargle

## You can delete pokemons above, but I guess most people would
## would agree that those are tradeable for extra candies.

## Add your own below:
- Cranidos
- Shieldon