## How to use:
# 1. Set calcy as:
# - No Moves:
#    "$NaAb$$Form$$Legacy$$Perf/IV%$ $Lvl$            $CatchDate$|$Lucky$|$ATT$|$DEF$|$HP$|$Gender$|$Trade$|$IV%Min$|$IV%Max$|$AttIV$|$DefIV$|$HpIV$|$FaMove$|$SpMove$|$Appraised$|$Legacy$"
# - Moves:
#    "$NaAb$$Form$$Legacy$$Perf/IV%$ $Lvl$            $CatchDate$|$Lucky$|$ATT$|$DEF$|$HP$|$Gender$|$Trade$|$IV%Min$|$IV%Max$|$AttIV$|$DefIV$|$HpIV$|$FaMove$|$SpMove$|$Appraised$|$Legacy$"
# 2. Search for:
#    "costume&!shiny, eggsonly&!shiny"
#   To rename costume pokemon differently
#
# TIP: You can also restore calcy's export: shiny-default.properties instead of copying and pasting the strings above.
#      Be aware it's going to replace your symbols as well.


# Nobrainer:
- conditions:
    success: false
  actions:
    rename: "! Verify"

# Appraise everyhing that's not appraised yet
- conditions:
    appraised: false
  actions:
    appraise:

## Costume babies with hearts ...
##    .... because ... babies aaaand:
## IV 100 (or really close but not possible to determine)
- conditions:
    name__in: !include ../pokemons/babies.yaml
    iv_max__eq: 100
    appraised: true
  actions:
    rename: "♠♥✓{calcy}"

## Costume babies with hearts ...
##    .... because ... babies.
- conditions:
    name__in: !include ../pokemons/babies.yaml
  actions:
    rename: "♠♥{calcy}"

## IV 100 (or really close but not possible to determine)
- conditions:
    iv_max__eq: 100
    appraised: true
  actions:
    rename: "♠✓{calcy}"

# Everything else
- actions:
    rename: "♠{calcy}"
